// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTSTB.Data;

#nullable disable

namespace QLTSTB.Migrations
{
    [DbContext(typeof(QLTSTBDbContext))]
    partial class QLTSTBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTSTB.Data.KiemKe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("NgayKiemKe")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThietBiID")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiVanPhongID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ThietBiVanPhongID");

                    b.ToTable("KiemKes");
                });

            modelBuilder.Entity("QLTSTB.Data.LoaiThietBi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiThietBis");
                });

            modelBuilder.Entity("QLTSTB.Data.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("QLTSTB.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongBanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhongBanID");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QLTSTB.Data.PhieuBaoTri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBaoTri")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThietBiID")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiVanPhongID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ThietBiVanPhongID");

                    b.ToTable("PhieuBaoTris");
                });

            modelBuilder.Entity("QLTSTB.Data.PhieuCapPhat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("NgayCapPhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiID")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiVanPhongID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("ThietBiVanPhongID");

                    b.ToTable("PhieuCapPhats");
                });

            modelBuilder.Entity("QLTSTB.Data.PhongBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("QLTSTB.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QLTSTB.Data.ThietBiVanPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiThietBiID")
                        .HasColumnType("int");

                    b.Property<string>("MaThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongBanID")
                        .HasColumnType("int");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiThietBiID");

                    b.HasIndex("PhongBanID");

                    b.ToTable("ThietBiVanPhongs");
                });

            modelBuilder.Entity("QLTSTB.Data.KiemKe", b =>
                {
                    b.HasOne("QLTSTB.Data.ThietBiVanPhong", "ThietBiVanPhong")
                        .WithMany("KiemKes")
                        .HasForeignKey("ThietBiVanPhongID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThietBiVanPhong");
                });

            modelBuilder.Entity("QLTSTB.Data.NhanVien", b =>
                {
                    b.HasOne("QLTSTB.Data.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("QLTSTB.Data.PhieuBaoTri", b =>
                {
                    b.HasOne("QLTSTB.Data.ThietBiVanPhong", "ThietBiVanPhong")
                        .WithMany("PhieuBaoTris")
                        .HasForeignKey("ThietBiVanPhongID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThietBiVanPhong");
                });

            modelBuilder.Entity("QLTSTB.Data.PhieuCapPhat", b =>
                {
                    b.HasOne("QLTSTB.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLTSTB.Data.ThietBiVanPhong", "ThietBiVanPhong")
                        .WithMany("PhieuCapPhats")
                        .HasForeignKey("ThietBiVanPhongID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("ThietBiVanPhong");
                });

            modelBuilder.Entity("QLTSTB.Data.TaiKhoan", b =>
                {
                    b.HasOne("QLTSTB.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLTSTB.Data.ThietBiVanPhong", b =>
                {
                    b.HasOne("QLTSTB.Data.LoaiThietBi", "LoaiThietBi")
                        .WithMany("ThietBiVanPhongs")
                        .HasForeignKey("LoaiThietBiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLTSTB.Data.PhongBan", "PhongBan")
                        .WithMany("ThietBiVanPhongs")
                        .HasForeignKey("PhongBanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiThietBi");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("QLTSTB.Data.LoaiThietBi", b =>
                {
                    b.Navigation("ThietBiVanPhongs");
                });

            modelBuilder.Entity("QLTSTB.Data.PhongBan", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("ThietBiVanPhongs");
                });

            modelBuilder.Entity("QLTSTB.Data.ThietBiVanPhong", b =>
                {
                    b.Navigation("KiemKes");

                    b.Navigation("PhieuBaoTris");

                    b.Navigation("PhieuCapPhats");
                });
#pragma warning restore 612, 618
        }
    }
}
